name: artifacts-download-trigger Download

on:
  push:
    branches: [ main, 'feature/*' ]
    paths:
      - 'artifacts-download-trigger/**'
  pull_request:
    branches: [ main, 'feature/*' ]
    paths:
      - 'artifacts-download-trigger/**'
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 60
  download-latest:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-upload.yml
          name: artifact
          path: artifact
          download-artifacts: true
          force-trigger: true
          gh-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
  download-branch:
    runs-on: ubuntu-latest
    needs: [ wait, download-latest ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-upload.yml
          name: artifact
          path: artifact
          branch: main
          download-artifacts: true
          force-trigger: true
          gh-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
  download-pr:
    runs-on: ubuntu-latest
    needs: [ wait, download-latest ]
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-upload.yml
          name: artifact
          path: artifact
          pr: ${{github.event.pull_request.number}}
          gh-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          download-artifacts: true
          force-trigger: true
      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
  download-multiple:
    runs-on: ubuntu-latest
    needs: [ wait, download-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-upload.yml
          download-artifacts: true
          force-trigger: true
          gh-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
      - name: Test
        run: |
          cat artifact1/sha1 | grep $GITHUB_SHA
          cat artifact2/sha2 | grep $GITHUB_SHA
  download-conclusion:
    runs-on: ubuntu-latest
    needs: [ wait, download-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: ./artifacts-download-trigger
        with:
          workflow: artifacts-download-trigger-upload.yml
          name: artifact
          path: artifact
          workflow-conclusion: ''
          download-artifacts: true
          force-trigger: true
          gh-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
